package shuttlePlaylistMakerButtons;

import javax.swing.ListSelectionModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jzhang
 */
public class FileSelectionButtons extends javax.swing.JPanel {

    /**
     * Creates new form FileSelection
     */
    public FileSelectionButtons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locationChooser = new javax.swing.JPanel();
        playlistLocation = new javax.swing.JPanel();
        playlistLocationLabel = new javax.swing.JLabel();
        playlistLocationButton = new javax.swing.JButton();
        convertedPlaylistLocation = new javax.swing.JPanel();
        storageLocationLabel = new javax.swing.JLabel();
        storageLocationButton = new javax.swing.JButton();
        utilitiesPanel = new javax.swing.JPanel();
        selectedFilesPanel = new javax.swing.JPanel();
        locationLabel = new javax.swing.JLabel();
        selectedFilesScrollPane1 = new javax.swing.JScrollPane();
        selectedFilesList = new javax.swing.JList();
        removeFilesPanel = new javax.swing.JPanel();
        removeLabel = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();
        convertButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(28000, 28000));
        setLayout(new java.awt.GridLayout(3, 0, 0, 20));

        locationChooser.setLayout(new java.awt.GridLayout(1, 0, 20, 10));

        playlistLocation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        playlistLocation.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        playlistLocationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playlistLocationLabel.setText("Select file/s to convert");
        playlistLocation.add(playlistLocationLabel);

        playlistLocationButton.setText("Select playlist/s");
        playlistLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playlistLocationButtonActionPerformed(evt);
            }
        });
        playlistLocation.add(playlistLocationButton);

        locationChooser.add(playlistLocation);

        convertedPlaylistLocation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        convertedPlaylistLocation.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        storageLocationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        storageLocationLabel.setText("Select location to save in");
        convertedPlaylistLocation.add(storageLocationLabel);

        storageLocationButton.setText("Select storage location");
        convertedPlaylistLocation.add(storageLocationButton);

        locationChooser.add(convertedPlaylistLocation);

        add(locationChooser);

        utilitiesPanel.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        selectedFilesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        selectedFilesPanel.setLayout(new java.awt.BorderLayout());

        locationLabel.setText("Location: ");
        locationLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        selectedFilesPanel.add(locationLabel, java.awt.BorderLayout.CENTER);

        selectedFilesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "File 1", "File 2", "File 3", "File 4", "File 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        selectedFilesList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        selectedFilesScrollPane1.setViewportView(selectedFilesList);

        selectedFilesPanel.add(selectedFilesScrollPane1, java.awt.BorderLayout.PAGE_START);

        utilitiesPanel.add(selectedFilesPanel);

        removeFilesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        removeFilesPanel.setLayout(new java.awt.GridLayout(2, 0));

        removeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removeLabel.setText("Remove selected files");
        removeFilesPanel.add(removeLabel);

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        removeFilesPanel.add(removeButton);

        utilitiesPanel.add(removeFilesPanel);

        add(utilitiesPanel);

        convertButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        convertButton.setText("Convert");
        add(convertButton);
    }// </editor-fold>//GEN-END:initComponents

    private void playlistLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playlistLocationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playlistLocationButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertButton;
    private javax.swing.JPanel convertedPlaylistLocation;
    private javax.swing.JPanel locationChooser;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JPanel playlistLocation;
    private javax.swing.JButton playlistLocationButton;
    private javax.swing.JLabel playlistLocationLabel;
    private javax.swing.JButton removeButton;
    private javax.swing.JPanel removeFilesPanel;
    private javax.swing.JLabel removeLabel;
    private javax.swing.JList selectedFilesList;
    private javax.swing.JPanel selectedFilesPanel;
    private javax.swing.JScrollPane selectedFilesScrollPane1;
    private javax.swing.JButton storageLocationButton;
    private javax.swing.JLabel storageLocationLabel;
    private javax.swing.JPanel utilitiesPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the convertButton
     */
    public javax.swing.JButton getConvertButton() {
        return convertButton;
    }

    /**
     * @param convertButton the convertButton to set
     */
    public void setConvertButton(javax.swing.JButton convertButton) {
        this.convertButton = convertButton;
    }

    /**
     * @return the convertedPlaylistLocation
     */
    public javax.swing.JPanel getConvertedPlaylistLocation() {
        return convertedPlaylistLocation;
    }

    /**
     * @param convertedPlaylistLocation the convertedPlaylistLocation to set
     */
    public void setConvertedPlaylistLocation(javax.swing.JPanel convertedPlaylistLocation) {
        this.convertedPlaylistLocation = convertedPlaylistLocation;
    }

    /**
     * @return the locationChooser
     */
    public javax.swing.JPanel getLocationChooser() {
        return locationChooser;
    }

    /**
     * @param locationChooser the locationChooser to set
     */
    public void setLocationChooser(javax.swing.JPanel locationChooser) {
        this.locationChooser = locationChooser;
    }

    /**
     * @return the locationLabel
     */
    public javax.swing.JLabel getLocationLabel() {
        return locationLabel;
    }

    /**
     * @param locationLabel the locationLabel to set
     */
    public void setLocationLabel(javax.swing.JLabel locationLabel) {
        this.locationLabel = locationLabel;
    }

    /**
     * @return the playlistLocation
     */
    public javax.swing.JPanel getPlaylistLocation() {
        return playlistLocation;
    }

    /**
     * @param playlistLocation the playlistLocation to set
     */
    public void setPlaylistLocation(javax.swing.JPanel playlistLocation) {
        this.playlistLocation = playlistLocation;
    }

    /**
     * @return the playlistLocationButton
     */
    public javax.swing.JButton getPlaylistLocationButton() {
        return playlistLocationButton;
    }

    /**
     * @param playlistLocationButton the playlistLocationButton to set
     */
    public void setPlaylistLocationButton(javax.swing.JButton playlistLocationButton) {
        this.playlistLocationButton = playlistLocationButton;
    }

    /**
     * @return the playlistLocationLabel
     */
    public javax.swing.JLabel getPlaylistLocationLabel() {
        return playlistLocationLabel;
    }

    /**
     * @param playlistLocationLabel the playlistLocationLabel to set
     */
    public void setPlaylistLocationLabel(javax.swing.JLabel playlistLocationLabel) {
        this.playlistLocationLabel = playlistLocationLabel;
    }

    /**
     * @return the removeButton
     */
    public javax.swing.JButton getRemoveButton() {
        return removeButton;
    }

    /**
     * @param removeButton the removeButton to set
     */
    public void setRemoveButton(javax.swing.JButton removeButton) {
        this.removeButton = removeButton;
    }

    /**
     * @return the removeFilesPanel
     */
    public javax.swing.JPanel getRemoveFilesPanel() {
        return removeFilesPanel;
    }

    /**
     * @param removeFilesPanel the removeFilesPanel to set
     */
    public void setRemoveFilesPanel(javax.swing.JPanel removeFilesPanel) {
        this.removeFilesPanel = removeFilesPanel;
    }

    /**
     * @return the removeLabel
     */
    public javax.swing.JLabel getRemoveLabel() {
        return removeLabel;
    }

    /**
     * @param removeLabel the removeLabel to set
     */
    public void setRemoveLabel(javax.swing.JLabel removeLabel) {
        this.removeLabel = removeLabel;
    }

    /**
     * @return the selectedFilesList
     */
    public javax.swing.JList getSelectedFilesList() {
        return selectedFilesList;
    }

    /**
     * @param selectedFilesList the selectedFilesList to set
     */
    public void setSelectedFilesList(javax.swing.JList selectedFilesList) {
        this.selectedFilesList = selectedFilesList;
    }

    /**
     * @return the selectedFilesPanel
     */
    public javax.swing.JPanel getSelectedFilesPanel() {
        return selectedFilesPanel;
    }

    /**
     * @param selectedFilesPanel the selectedFilesPanel to set
     */
    public void setSelectedFilesPanel(javax.swing.JPanel selectedFilesPanel) {
        this.selectedFilesPanel = selectedFilesPanel;
    }

    /**
     * @return the selectedFilesScrollPane1
     */
    public javax.swing.JScrollPane getSelectedFilesScrollPane1() {
        return selectedFilesScrollPane1;
    }

    /**
     * @param selectedFilesScrollPane1 the selectedFilesScrollPane1 to set
     */
    public void setSelectedFilesScrollPane1(javax.swing.JScrollPane selectedFilesScrollPane1) {
        this.selectedFilesScrollPane1 = selectedFilesScrollPane1;
    }

    /**
     * @return the storageLocationButton
     */
    public javax.swing.JButton getStorageLocationButton() {
        return storageLocationButton;
    }

    /**
     * @param storageLocationButton the storageLocationButton to set
     */
    public void setStorageLocationButton(javax.swing.JButton storageLocationButton) {
        this.storageLocationButton = storageLocationButton;
    }

    /**
     * @return the storageLocationLabel
     */
    public javax.swing.JLabel getStorageLocationLabel() {
        return storageLocationLabel;
    }

    /**
     * @param storageLocationLabel the storageLocationLabel to set
     */
    public void setStorageLocationLabel(javax.swing.JLabel storageLocationLabel) {
        this.storageLocationLabel = storageLocationLabel;
    }

    /**
     * @return the utilitiesPanel
     */
    public javax.swing.JPanel getUtilitiesPanel() {
        return utilitiesPanel;
    }

    /**
     * @param utilitiesPanel the utilitiesPanel to set
     */
    public void setUtilitiesPanel(javax.swing.JPanel utilitiesPanel) {
        this.utilitiesPanel = utilitiesPanel;
    }
}
